// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juhtsjzrszzysadwhgjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1aHRzanpyc3p6eXNhZHdoZ2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTM5MzcsImV4cCI6MjA2MjE4OTkzN30.6E3zXuObJaU2qkPBOtUfywvEAOXLrpG0Tzlc1HvFwmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);